# 3.4 Get the Data 

* The full Jupyter notebook is available at https://github.com/ageron/handson-ml
* https://github.com/ageron/handson-ml/tree/master/datasets/insurance

In [28]:
import pandas as pd # 輸入
insurance = pd.read_csv("data/lec03-insurance.csv") # 資料夾 data 下 lec03-insurance.csv
insurance.head(2) 

age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18     NaN  33.77         1     no  southeast   1725.5523

In [29]:
insurance.head() 

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18     NaN  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [30]:
insurance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
age         1338 non-null int64
sex         1337 non-null object
bmi         1337 non-null float64
children    1338 non-null int64
smoker      1338 non-null object
region      1338 non-null object
charges     1338 non-null float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.2+ KB


In [31]:
insurance.shape

(1338, 7)

In [32]:
insurance.age

0       19
1       18
2       28
3       33
4       32
5       31
6       46
7       37
8       37
9       60
10      25
11      62
12      23
13      56
14      27
15      19
16      52
17      23
18      56
19      30
20      60
21      30
22      18
23      34
24      37
25      59
26      63
27      55
28      23
29      31
        ..
1308    25
1309    41
1310    42
1311    33
1312    34
1313    19
1314    30
1315    18
1316    19
1317    18
1318    35
1319    39
1320    31
1321    62
1322    62
1323    42
1324    31
1325    61
1326    42
1327    51
1328    23
1329    52
1330    57
1331    23
1332    52
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

In [33]:
insurance['age']

0       19
1       18
2       28
3       33
4       32
5       31
6       46
7       37
8       37
9       60
10      25
11      62
12      23
13      56
14      27
15      19
16      52
17      23
18      56
19      30
20      60
21      30
22      18
23      34
24      37
25      59
26      63
27      55
28      23
29      31
        ..
1308    25
1309    41
1310    42
1311    33
1312    34
1313    19
1314    30
1315    18
1316    19
1317    18
1318    35
1319    39
1320    31
1321    62
1322    62
1323    42
1324    31
1325    61
1326    42
1327    51
1328    23
1329    52
1330    57
1331    23
1332    52
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

In [34]:
insurance.iloc[:,0] 

0       19
1       18
2       28
3       33
4       32
5       31
6       46
7       37
8       37
9       60
10      25
11      62
12      23
13      56
14      27
15      19
16      52
17      23
18      56
19      30
20      60
21      30
22      18
23      34
24      37
25      59
26      63
27      55
28      23
29      31
        ..
1308    25
1309    41
1310    42
1311    33
1312    34
1313    19
1314    30
1315    18
1316    19
1317    18
1318    35
1319    39
1320    31
1321    62
1322    62
1323    42
1324    31
1325    61
1326    42
1327    51
1328    23
1329    52
1330    57
1331    23
1332    52
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

In [35]:
insurance.head(2)

age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18     NaN  33.77         1     no  southeast   1725.5523

In [36]:
insurance.iloc[1]

age                18
sex               NaN
bmi             33.77
children            1
smoker             no
region      southeast
charges       1725.55
Name: 1, dtype: object

In [37]:
insurance.head(2)

age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18     NaN  33.77         1     no  southeast   1725.5523

In [38]:
insurance.iloc[0, 5], insurance['region'][0]

('southwest', 'southwest')

In [39]:
insurance.head(2)

age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18     NaN  33.77         1     no  southeast   1725.5523

In [40]:
insurance.iloc[0, 5:] 

region     southwest
charges      16884.9
Name: 0, dtype: object

In [41]:
insurance.head(2)

age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18     NaN  33.77         1     no  southeast   1725.5523

In [45]:
insurance.iloc[1, 1:3] 

sex      NaN
bmi    33.77
Name: 1, dtype: object

In [46]:
insurance.describe()

age          bmi     children       charges
count  1338.000000  1337.000000  1338.000000   1338.000000
mean     39.207025    30.667004     1.094918  13270.422265
std      14.049960     6.099040     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.315000     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.700000     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [47]:
insurance.age.mean(), insurance.describe().iloc[1, 0]

(39.20702541106129, 39.20702541106129)

In [48]:
insurance.describe().iloc[4:7, 0]

25%    27.0
50%    39.0
75%    51.0
Name: age, dtype: float64

# 3.4.2 Nominal data (名目資料)

In [49]:
insurance.head(2)

age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18     NaN  33.77         1     no  southeast   1725.5523

In [51]:
insurance.region.describe()

count          1338
unique            4
top       southeast
freq            364
Name: region, dtype: object

In [59]:
364/1338, insurance.region.describe()[3] / insurance.region.describe()[0]

(0.27204783258594917, 0.27204783258594917)

In [60]:
insurance.describe(include = 'all')

age   sex          bmi     children smoker     region  \
count   1338.000000  1337  1337.000000  1338.000000   1338       1338   
unique          NaN     2          NaN          NaN      2          4   
top             NaN  male          NaN          NaN     no  southeast   
freq            NaN   675          NaN          NaN   1064        364   
mean      39.207025   NaN    30.667004     1.094918    NaN        NaN   
std       14.049960   NaN     6.099040     1.205493    NaN        NaN   
min       18.000000   NaN    15.960000     0.000000    NaN        NaN   
25%       27.000000   NaN    26.315000     0.000000    NaN        NaN   
50%       39.000000   NaN    30.400000     1.000000    NaN        NaN   
75%       51.000000   NaN    34.700000     2.000000    NaN        NaN   
max       64.000000   NaN    53.130000     5.000000    NaN        NaN   

             charges  
count    1338.000000  
unique           NaN  
top              NaN  
freq             NaN  
mean    13270.422265  
std     12110.011237  
min      1121.873900  
25%      4740.287150  
50%      9382.033000  
75%     16639.912515  
max     63770.428010

In [61]:
c = insurance.region.astype('category').values
c

[southwest, southeast, southeast, northwest, northwest, ..., northwest, northeast, southeast, southwest, northwest]
Length: 1338
Categories (4, object): [northeast, northwest, southeast, southwest]

In [63]:
c.value_counts()

northeast    324
northwest    325
southeast    364
southwest    325
dtype: int64

In [65]:
insurance.region.value_counts()

southeast    364
southwest    325
northwest    325
northeast    324
Name: region, dtype: int64

# 3.4.3 NumPy 

In [66]:
import numpy as np
A = np.array([2, 2, 4, 80])
np.mean(A), np.median(A) #平均、中位數

(22.0, 3.0)

In [5]:
import numpy as np
from scipy import stats # scipy also include pandas and NumPy
A = np.array([2, 2, 2, 4, 80])
print(stats.mode(A))
# ModeResult(mode=array([2]), count=array([3]))
print(stats.mode(A)[0][0], stats.mode(A)[1][0]) # 2, 3 

ModeResult(mode=array([2]), count=array([3]))
2 3


In [68]:
B = np.array([2, 2, 4, 8])
np.var(B), np.std(B), [np.min(B), np.max(B)]

(6.0, 2.449489742783178, [2, 8])

## 2-dim array 

In [69]:
import numpy as np
b = np.array(([4, 5, 1], [6, 2, 7]))
b

array([[4, 5, 1],
       [6, 2, 7]])

In [70]:
b.shape, b.shape[0], b.shape[1] # 形狀

((2, 3), 2, 3)

In [73]:
b

array([[4, 5, 1],
       [6, 2, 7]])

In [71]:
b[:, 2]

array([1, 7])

In [72]:
b[1]

array([6, 2, 7])

In [74]:
b[:, 0:2] 

array([[4, 5],
       [6, 2]])

In [75]:
np.zeros((2,3)) 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [76]:
np.eye(3,3) # identity matrix (單位矩陣)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 3.4.4 Create a Test Set

In [77]:
import numpy as np
np.random.permutation(5)

array([3, 4, 0, 1, 2])

In [78]:
import numpy as np
np.random.permutation(5)

array([1, 3, 0, 2, 4])

In [79]:
np.random.seed(42)
shuffled_indices = np.random.permutation(5)
print(shuffled_indices, shuffled_indices[:3], shuffled_indices[3:])

[1 4 2 0 3] [1 4 2] [0 3]


In [80]:
np.random.seed(42)
shuffled_indices = np.random.permutation(5)
print(shuffled_indices, shuffled_indices[:3], shuffled_indices[3:])

[1 4 2 0 3] [1 4 2] [0 3]


In [81]:
import numpy as np

# For illustration only. Sklearn has train_test_split()
def split_train_test(data, test_ratio):
    # to make this notebook's output identical at every run
    np.random.seed(42)
    shuffled_indices = np.random.permutation(len(data))
    test_set_size = int(len(data) * test_ratio)
    test_indices = shuffled_indices[:test_set_size]
    train_indices = shuffled_indices[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

In [82]:
train_set, test_set = split_train_test(insurance, 0.2)
print(len(train_set), "train +", len(test_set), "test", ' = total ',  len(train_set) + len(test_set))

1071 train + 267 test  = total  1338


In [83]:
train_set.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1071 entries, 846 to 1126
Data columns (total 7 columns):
age         1071 non-null int64
sex         1070 non-null object
bmi         1070 non-null float64
children    1071 non-null int64
smoker      1071 non-null object
region      1071 non-null object
charges     1071 non-null float64
dtypes: float64(2), int64(2), object(3)
memory usage: 66.9+ KB


In [84]:
test_set.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 267 entries, 764 to 543
Data columns (total 7 columns):
age         267 non-null int64
sex         267 non-null object
bmi         267 non-null float64
children    267 non-null int64
smoker      267 non-null object
region      267 non-null object
charges     267 non-null float64
dtypes: float64(2), int64(2), object(3)
memory usage: 16.7+ KB


In [85]:
train_set.head(2)

age     sex    bmi  children smoker     region    charges
846   51  female  34.20         1     no  southwest  9872.7010
560   46  female  19.95         2     no  northwest  9193.8385

### another approach

In [89]:
insurance.iloc[0:2, :]

age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18     NaN  33.77         1     no  southeast   1725.5523

In [96]:
from sklearn.model_selection import train_test_split 
# Split dataset
X_train, X_test, Y_train, Y_test = train_test_split(insurance.iloc[:, 0:6], insurance.iloc[:, 6], test_size=0.2, random_state = 42)

In [97]:
train_set.head(2)

age     sex    bmi  children smoker     region    charges
846   51  female  34.20         1     no  southwest  9872.7010
560   46  female  19.95         2     no  northwest  9193.8385

In [98]:
X_train.head(2)

age     sex    bmi  children smoker     region
560    46  female  19.95         2     no  northwest
1285   47  female  24.32         0     no  northeast

In [99]:
Y_train.head(2)

560     9193.8385
1285    8534.6718
Name: charges, dtype: float64